attempt_6 fitness #4: 50 stages of human-intent extracts

diff --git a/attempt_6/intent_samples/SkillPanel_friendly-id__J8toJ21/mvnw.diff b/attempt_6/intent_samples/SkillPanel_friendly-id__J8toJ21/mvnw.diff
--- a/attempt_6/intent_samples/SkillPanel_friendly-id__J8toJ21/mvnw.diff
+++ b/attempt_6/intent_samples/SkillPanel_friendly-id__J8toJ21/mvnw.diff
@@ -254,4 +254,192 @@ index e96ccd5..bd8896b 100755
 -      else
 -        javaExecutable="`readlink -f \"$javaExecutable\"`"
 -      fi
--      javaHome="`dirname
+-      javaHome="`dirname \"$javaExecutable\"`"
+-      javaHome=`expr "$javaHome" : '\(.*\)/bin'`
+-      JAVA_HOME="$javaHome"
+-      export JAVA_HOME
+-    fi
+-  fi
++# verbose opt
++__MVNW_QUIET_WGET=--quiet __MVNW_QUIET_CURL=--silent __MVNW_QUIET_UNZIP=-q __MVNW_QUIET_TAR=''
++[ "${MVNW_VERBOSE-}" != true ] || __MVNW_QUIET_WGET='' __MVNW_QUIET_CURL='' __MVNW_QUIET_UNZIP='' __MVNW_QUIET_TAR=v
++
++# normalize http auth
++case "${MVNW_PASSWORD:+has-password}" in
++'') MVNW_USERNAME='' MVNW_PASSWORD='' ;;
++has-password) [ -n "${MVNW_USERNAME-}" ] || MVNW_USERNAME='' MVNW_PASSWORD='' ;;
++esac
++
++if [ -z "${MVNW_USERNAME-}" ] && command -v wget >/dev/null; then
++  verbose "Found wget ... using wget"
++  wget ${__MVNW_QUIET_WGET:+"$__MVNW_QUIET_WGET"} "$distributionUrl" -O "$TMP_DOWNLOAD_DIR/$distributionUrlName" || die "wget: Failed to fetch $distributionUrl"
++elif [ -z "${MVNW_USERNAME-}" ] && command -v curl >/dev/null; then
++  verbose "Found curl ... using curl"
++  curl ${__MVNW_QUIET_CURL:+"$__MVNW_QUIET_CURL"} -f -L -o "$TMP_DOWNLOAD_DIR/$distributionUrlName" "$distributionUrl" || die "curl: Failed to fetch $distributionUrl"
++elif set_java_home; then
++  verbose "Falling back to use Java to download"
++  javaSource="$TMP_DOWNLOAD_DIR/Downloader.java"
++  targetZip="$TMP_DOWNLOAD_DIR/$distributionUrlName"
++  cat >"$javaSource" <<-END
++	public class Downloader extends java.net.Authenticator
++	{
++	  protected java.net.PasswordAuthentication getPasswordAuthentication()
++	  {
++	    return new java.net.PasswordAuthentication( System.getenv( "MVNW_USERNAME" ), System.getenv( "MVNW_PASSWORD" ).toCharArray() );
++	  }
++	  public static void main( String[] args ) throws Exception
++	  {
++	    setDefault( new Downloader() );
++	    java.nio.file.Files.copy( java.net.URI.create( args[0] ).toURL().openStream(), java.nio.file.Paths.get( args[1] ).toAbsolutePath().normalize() );
++	  }
++	}
++	END
++  # For Cygwin/MinGW, switch paths to Windows format before running javac and java
++  verbose " - Compiling Downloader.java ..."
++  "$(native_path "$JAVACCMD")" "$(native_path "$javaSource")" || die "Failed to compile Downloader.java"
++  verbose " - Running Downloader.java ..."
++  "$(native_path "$JAVACMD")" -cp "$(native_path "$TMP_DOWNLOAD_DIR")" Downloader "$distributionUrl" "$(native_path "$targetZip")"
+ fi
+ 
+-if [ -z "$JAVACMD" ] ; then
+-  if [ -n "$JAVA_HOME"  ] ; then
+-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+-      # IBM's JDK on AIX uses strange locations for the executables
+-      JAVACMD="$JAVA_HOME/jre/sh/java"
+-    else
+-      JAVACMD="$JAVA_HOME/bin/java"
++# If specified, validate the SHA-256 sum of the Maven distribution zip file
++if [ -n "${distributionSha256Sum-}" ]; then
++  distributionSha256Result=false
++  if [ "$MVN_CMD" = mvnd.sh ]; then
++    echo "Checksum validation is not supported for maven-mvnd." >&2
++    echo "Please disable validation by removing 'distributionSha256Sum' from your maven-wrapper.properties." >&2
++    exit 1
++  elif command -v sha256sum >/dev/null; then
++    if echo "$distributionSha256Sum  $TMP_DOWNLOAD_DIR/$distributionUrlName" | sha256sum -c - >/dev/null 2>&1; then
++      distributionSha256Result=true
++    fi
++  elif command -v shasum >/dev/null; then
++    if echo "$distributionSha256Sum  $TMP_DOWNLOAD_DIR/$distributionUrlName" | shasum -a 256 -c >/dev/null 2>&1; then
++      distributionSha256Result=true
+     fi
+   else
+-    JAVACMD="`which java`"
++    echo "Checksum validation was requested but neither 'sha256sum' or 'shasum' are available." >&2
++    echo "Please install either command, or disable validation by removing 'distributionSha256Sum' from your maven-wrapper.properties." >&2
++    exit 1
++  fi
++  if [ $distributionSha256Result = false ]; then
++    echo "Error: Failed to validate Maven distribution SHA-256, your Maven distribution might be compromised." >&2
++    echo "If you updated your Maven version, you need to update the specified distributionSha256Sum property." >&2
++    exit 1
+   fi
+ fi
+ 
+-if [ ! -x "$JAVACMD" ] ; then
+-  echo "Error: JAVA_HOME is not defined correctly." >&2
+-  echo "  We cannot execute $JAVACMD" >&2
+-  exit 1
+-fi
+-
+-if [ -z "$JAVA_HOME" ] ; then
+-  echo "Warning: JAVA_HOME environment variable is not set."
++# unzip and move
++if command -v unzip >/dev/null; then
++  unzip ${__MVNW_QUIET_UNZIP:+"$__MVNW_QUIET_UNZIP"} "$TMP_DOWNLOAD_DIR/$distributionUrlName" -d "$TMP_DOWNLOAD_DIR" || die "failed to unzip"
++else
++  tar xzf${__MVNW_QUIET_TAR:+"$__MVNW_QUIET_TAR"} "$TMP_DOWNLOAD_DIR/$distributionUrlName" -C "$TMP_DOWNLOAD_DIR" || die "failed to untar"
+ fi
+ 
+-CLASSWORLDS_LAUNCHER=org.codehaus.plexus.classworlds.launcher.Launcher
+-
+-# traverses directory structure from process work directory to filesystem root
+-# first directory with .mvn subdirectory is considered project base directory
+-find_maven_basedir() {
++# Find the actual extracted directory name (handles snapshots where filename != directory name)
++actualDistributionDir=""
+ 
+-  if [ -z "$1" ]
+-  then
+-    echo "Path not specified to find_maven_basedir"
+-    return 1
++# First try the expected directory name (for regular distributions)
++if [ -d "$TMP_DOWNLOAD_DIR/$distributionUrlNameMain" ]; then
++  if [ -f "$TMP_DOWNLOAD_DIR/$distributionUrlNameMain/bin/$MVN_CMD" ]; then
++    actualDistributionDir="$distributionUrlNameMain"
+   fi
++fi
+ 
+-  basedir="$1"
+-  wdir="$1"
+-  while [ "$wdir" != '/' ] ; do
+-    if [ -d "$wdir"/.mvn ] ; then
+-      basedir=$wdir
+-      break
+-    fi
+-    # workaround for JBEAP-8937 (on Solaris 10/Sparc)
+-    if [ -d "${wdir}" ]; then
+-      wdir=`cd "$wdir/.."; pwd`
++# If not found, search for any directory with the Maven executable (for snapshots)
++if [ -z "$actualDistributionDir" ]; then
++  # enable globbing to iterate over items
++  set +f
++  for dir in "$TMP_DOWNLOAD_DIR"/*; do
++    if [ -d "$dir" ]; then
++      if [ -f "$dir/bin/$MVN_CMD" ]; then
++        actualDistributionDir="$(basename "$dir")"
++        break
++      fi
+     fi
+-    # end of workaround
+   done
+-  echo "${basedir}"
+-}
+-
+-# concatenates all lines of a file
+-concat_lines() {
+-  if [ -f "$1" ]; then
+-    echo "$(tr -s '\n' ' ' < "$1")"
+-  fi
+-}
+-
+-BASE_DIR=`find_maven_basedir "$(pwd)"`
+-if [ -z "$BASE_DIR" ]; then
+-  exit 1;
++  set -f
+ fi
+ 
+-export MAVEN_PROJECTBASEDIR=${MAVEN_BASEDIR:-"$BASE_DIR"}
+-if [ "$MVNW_VERBOSE" = true ]; then
+-  echo $MAVEN_PROJECTBASEDIR
+-fi
+-MAVEN_OPTS="$(concat_lines "$MAVEN_PROJECTBASEDIR/.mvn/jvm.config") $MAVEN_OPTS"
+-
+-# For Cygwin, switch paths to Windows format before running java
+-if $cygwin; then
+-  [ -n "$M2_HOME" ] &&
+-    M2_HOME=`cygpath --path --windows "$M2_HOME"`
+-  [ -n "$JAVA_HOME" ] &&
+-    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+-  [ -n "$CLASSPATH" ] &&
+-    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+-  [ -n "$MAVEN_PROJECTBASEDIR" ] &&
+-    MAVEN_PROJECTBASEDIR=`cygpath --path --windows "$MAVEN_PROJECTBASEDIR"`
++if [ -z "$actualDistributionDir" ]; then
++  verbose "Contents of $TMP_DOWNLOAD_DIR:"
++  verbose "$(ls -la "$TMP_DOWNLOAD_DIR")"
++  die "Could not find Maven distribution directory in extracted archive"
+ fi
+ 
+-WRAPPER_LAUNCHER=org.apache.maven.wrapper.MavenWrapperMain
++verbose "Found extracted Maven distribution directory: $actualDistributionDir"
++printf %s\\n "$distributionUrl" >"$TMP_DOWNLOAD_DIR/$actualDistributionDir/mvnw.url"
++mv -- "$TMP_DOWNLOAD_DIR/$actualDistributionDir" "$MAVEN_HOME" || [ -d "$MAVEN_HOME" ] || die "fail to move MAVEN_HOME"
+ 
+-exec "$JAVACMD" \
+-  $MAVEN_OPTS \
+-  -classpath "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar" \
+-  "-Dmaven.home=${M2_HOME}" "-Dmaven.multiModuleProjectDirectory=${MAVEN_PROJECTBASEDIR}" \
+-  ${WRAPPER_LAUNCHER} $MAVEN_CONFIG "$@"
++clean || :
++exec_maven "$@"
diff --git a/attempt_6/intent_samples/sjucker_zkmf2024-server__J17toJ21/mvnw.diff b/attempt_6/intent_samples/sjucker_zkmf2024-server__J17toJ21/mvnw.diff
--- a/attempt_6/intent_samples/sjucker_zkmf2024-server__J17toJ21/mvnw.diff
+++ b/attempt_6/intent_samples/sjucker_zkmf2024-server__J17toJ21/mvnw.diff
@@ -259,4 +259,130 @@ index a16b543..8d937f4
 +        log "Found wget ... using wget"
 +        [ "$MVNW_VERBOSE" = true ] && QUIET="" || QUIET="--quiet"
          if [ -z "$MVNW_USERNAME" ] || [ -z "$MVNW_PASSWORD" ]; then
--            wget "$
+-            wget "$jarUrl" -O "$wrapperJarPath"
++            wget $QUIET "$wrapperUrl" -O "$wrapperJarPath" || rm -f "$wrapperJarPath"
+         else
+-            wget --http-user=$MVNW_USERNAME --http-password=$MVNW_PASSWORD "$jarUrl" -O "$wrapperJarPath"
++            wget $QUIET --http-user="$MVNW_USERNAME" --http-password="$MVNW_PASSWORD" "$wrapperUrl" -O "$wrapperJarPath" || rm -f "$wrapperJarPath"
+         fi
+     elif command -v curl > /dev/null; then
+-        if [ "$MVNW_VERBOSE" = true ]; then
+-          echo "Found curl ... using curl"
+-        fi
++        log "Found curl ... using curl"
++        [ "$MVNW_VERBOSE" = true ] && QUIET="" || QUIET="--silent"
+         if [ -z "$MVNW_USERNAME" ] || [ -z "$MVNW_PASSWORD" ]; then
+-            curl -o "$wrapperJarPath" "$jarUrl" -f
++            curl $QUIET -o "$wrapperJarPath" "$wrapperUrl" -f -L || rm -f "$wrapperJarPath"
+         else
+-            curl --user $MVNW_USERNAME:$MVNW_PASSWORD -o "$wrapperJarPath" "$jarUrl" -f
++            curl $QUIET --user "$MVNW_USERNAME:$MVNW_PASSWORD" -o "$wrapperJarPath" "$wrapperUrl" -f -L || rm -f "$wrapperJarPath"
+         fi
+-
+     else
+-        if [ "$MVNW_VERBOSE" = true ]; then
+-          echo "Falling back to using Java to download"
+-        fi
+-        javaClass="$BASE_DIR/.mvn/wrapper/MavenWrapperDownloader.java"
++        log "Falling back to using Java to download"
++        javaSource="$MAVEN_PROJECTBASEDIR/.mvn/wrapper/MavenWrapperDownloader.java"
++        javaClass="$MAVEN_PROJECTBASEDIR/.mvn/wrapper/MavenWrapperDownloader.class"
+         # For Cygwin, switch paths to Windows format before running javac
+         if $cygwin; then
+-          javaClass=`cygpath --path --windows "$javaClass"`
++          javaSource=$(cygpath --path --windows "$javaSource")
++          javaClass=$(cygpath --path --windows "$javaClass")
+         fi
+-        if [ -e "$javaClass" ]; then
+-            if [ ! -e "$BASE_DIR/.mvn/wrapper/MavenWrapperDownloader.class" ]; then
+-                if [ "$MVNW_VERBOSE" = true ]; then
+-                  echo " - Compiling MavenWrapperDownloader.java ..."
+-                fi
+-                # Compiling the Java class
+-                ("$JAVA_HOME/bin/javac" "$javaClass")
++        if [ -e "$javaSource" ]; then
++            if [ ! -e "$javaClass" ]; then
++                log " - Compiling MavenWrapperDownloader.java ..."
++                ("$JAVA_HOME/bin/javac" "$javaSource")
+             fi
+-            if [ -e "$BASE_DIR/.mvn/wrapper/MavenWrapperDownloader.class" ]; then
+-                # Running the downloader
+-                if [ "$MVNW_VERBOSE" = true ]; then
+-                  echo " - Running MavenWrapperDownloader.java ..."
+-                fi
+-                ("$JAVA_HOME/bin/java" -cp .mvn/wrapper MavenWrapperDownloader "$MAVEN_PROJECTBASEDIR")
++            if [ -e "$javaClass" ]; then
++                log " - Running MavenWrapperDownloader.java ..."
++                ("$JAVA_HOME/bin/java" -cp .mvn/wrapper MavenWrapperDownloader "$wrapperUrl" "$wrapperJarPath") || rm -f "$wrapperJarPath"
+             fi
+         fi
+     fi
+@@ -278,33 +251,58 @@ fi
+ # End of extension
+ ##########################################################################################
+ 
+-export MAVEN_PROJECTBASEDIR=${MAVEN_BASEDIR:-"$BASE_DIR"}
+-if [ "$MVNW_VERBOSE" = true ]; then
+-  echo $MAVEN_PROJECTBASEDIR
++# If specified, validate the SHA-256 sum of the Maven wrapper jar file
++wrapperSha256Sum=""
++while IFS="=" read -r key value; do
++  case "$key" in (wrapperSha256Sum) wrapperSha256Sum=$value; break ;;
++  esac
++done < "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.properties"
++if [ -n "$wrapperSha256Sum" ]; then
++  wrapperSha256Result=false
++  if command -v sha256sum > /dev/null; then
++    if echo "$wrapperSha256Sum  $wrapperJarPath" | sha256sum -c > /dev/null 2>&1; then
++      wrapperSha256Result=true
++    fi
++  elif command -v shasum > /dev/null; then
++    if echo "$wrapperSha256Sum  $wrapperJarPath" | shasum -a 256 -c > /dev/null 2>&1; then
++      wrapperSha256Result=true
++    fi
++  else
++    echo "Checksum validation was requested but neither 'sha256sum' or 'shasum' are available."
++    echo "Please install either command, or disable validation by removing 'wrapperSha256Sum' from your maven-wrapper.properties."
++    exit 1
++  fi
++  if [ $wrapperSha256Result = false ]; then
++    echo "Error: Failed to validate Maven wrapper SHA-256, your Maven wrapper might be compromised." >&2
++    echo "Investigate or delete $wrapperJarPath to attempt a clean download." >&2
++    echo "If you updated your Maven version, you need to update the specified wrapperSha256Sum property." >&2
++    exit 1
++  fi
+ fi
++
+ MAVEN_OPTS="$(concat_lines "$MAVEN_PROJECTBASEDIR/.mvn/jvm.config") $MAVEN_OPTS"
+ 
+ # For Cygwin, switch paths to Windows format before running java
+ if $cygwin; then
+-  [ -n "$M2_HOME" ] &&
+-    M2_HOME=`cygpath --path --windows "$M2_HOME"`
+   [ -n "$JAVA_HOME" ] &&
+-    JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
++    JAVA_HOME=$(cygpath --path --windows "$JAVA_HOME")
+   [ -n "$CLASSPATH" ] &&
+-    CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
++    CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
+   [ -n "$MAVEN_PROJECTBASEDIR" ] &&
+-    MAVEN_PROJECTBASEDIR=`cygpath --path --windows "$MAVEN_PROJECTBASEDIR"`
++    MAVEN_PROJECTBASEDIR=$(cygpath --path --windows "$MAVEN_PROJECTBASEDIR")
+ fi
+ 
+ # Provide a "standardized" way to retrieve the CLI args that will
+ # work with both Windows and non-Windows executions.
+-MAVEN_CMD_LINE_ARGS="$MAVEN_CONFIG $@"
++MAVEN_CMD_LINE_ARGS="$MAVEN_CONFIG $*"
+ export MAVEN_CMD_LINE_ARGS
+ 
+ WRAPPER_LAUNCHER=org.apache.maven.wrapper.MavenWrapperMain
+ 
++# shellcheck disable=SC2086 # safe args
+ exec "$JAVACMD" \
+   $MAVEN_OPTS \
++  $MAVEN_DEBUG_OPTS \
+   -classpath "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar" \
+-  "-Dmaven.home=${M2_HOME}" "-Dmaven.multiModuleProjectDirectory=${MAVEN_PROJECTBASEDIR}" \
++  "-Dmaven.multiModuleProjectDirectory=${MAVEN_PROJECTBASEDIR}" \
+   ${WRAPPER_LAUNCHER} $MAVEN_CONFIG "$@"
